set -x
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export NCCL_DEBUG=INFO
export NCCL_ALGO=ring
export NCCL_PROTO=ucp
export NCCL_SOCKET_IFNAME=bond1
export NCCL_MIN_NRINGS=1
export NCCL_IB_GID_INDEX=3
export GLOO_SOCKET_IFNAME=bond1
master_addr="30.159.160.47"
export MASTER_ADDR=$master_addr
master_port=14545
export MASTER_PORT=$master_port
export HOME=/apdcephfs_cq11/share_2973545/wenweiwwli/

export http_proxy="http://star-proxy.oa.com:3128"
export https_proxy="http://star-proxy.oa.com:3128"
export PATH=/usr/local/gcc/bin:$PATH
export PATH=/root/miniconda3/envs/zero/bin:$PATH
export VLLM_ATTENTION_BACKEND=XFORMERS
DATA_DIR=data/open_industry/v1
MODEL_PATH=~/models/qwen2.5-7b
ROLLOUT_TP_SIZE=4
n_gpus_per_node=8
nnodes=2
experiment_name='2node-Qwen-7B'

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=$DATA_DIR/train.parquet \
    data.val_files=$DATA_DIR/test.parquet\
    data.train_batch_size=16 \
    data.val_batch_size=16 \
    data.max_prompt_length=16384 \
    data.max_response_length=1024 \
    actor_rollout_ref.model.path=$MODEL_PATH\
    actor_rollout_ref.actor.optim.lr=3e-7 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=256 \
    actor_rollout_ref.actor.ppo_micro_batch_size=16 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.grad_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=1 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=$ROLLOUT_TP_SIZE \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.max_num_batched_tokens=null \
    actor_rollout_ref.ref.log_prob_micro_batch_size=1 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    +trainer.val_before_train=False \
    trainer.critic_warmup=0 \
    trainer.logger=['wandb'] \
    trainer.project_name='GRPO_OPEN_INDUSTRY' \
    trainer.experiment_name=$experiment_name \
    trainer.n_gpus_per_node=$n_gpus_per_node \
    trainer.nnodes=$nnodes \
    trainer.default_hdfs_dir=null \
    trainer.save_freq=30 \
    trainer.test_freq=10 \
    trainer.total_epochs=5 $@ 2>&1 | tee 7b_open_industry.log
